version: '3.8'

services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/
    ports:
      - 5000:80
      - 8000:8000
    networks:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony-demo
      MYSQL_USER: symfony-demo
      MYSQL_PASSWORD: symfony-demo
    networks:
      - mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password0
    networks:
      - mysql
networks:
  mysql:
volumes:
  db_data:

